[manifest]
version = "1.0.0"
dump_lua = true
priority = 5

# Card boost
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''
    G.E_MANAGER:add_event(Event({
      trigger = 'immediate',
      func = (function()
          G.SHOP_SIGN.alignment.offset.y = 0
          return true
      end)
    }))
'''
position = "after"
payload = '''
if G.GAME.modifiers.mstg_reroll_limit then
            local t = {
                n = G.UIT.ROOT,
                config = { align = 'cl', colour = G.C.CLEAR },
                nodes = {
                    UIBox_dyn_container({
                        {
                            n = G.UIT.C,
                            config = { align = "cm", padding = 0.1, emboss = 0.05, r = 0.1, colour = G.C.DYN_UI.BOSS_MAIN },
                            nodes = {
                                {
                                    n = G.UIT.R,
                                    config = { align = "cm", padding = 0.05 },
                                    nodes = {
                                        {
                                            n = G.UIT.C,
                                            config = { align = "cm", padding = 0.1 },
                                            nodes = {
                                                {
                                                    n = G.UIT.R,
                                                    config = { id = 'next_round_button', align = "cm", minw = 2.8, minh = 1.5, r = 0.15, colour = G.C.RED, one_press = true, button = 'toggle_shop', hover = true, shadow = true },
                                                    nodes = {
                                                        {
                                                            n = G.UIT.R,
                                                            config = { align = "cm", padding = 0.07, focus_args = { button = 'y', orientation = 'cr' }, func = 'set_button_pip' },
                                                            nodes = {
                                                                {
                                                                    n = G.UIT.R,
                                                                    config = { align = "cm", maxw = 1.3 },
                                                                    nodes = {
                                                                        { n = G.UIT.T, config = { text = localize('b_next_round_1'), scale = 0.4, colour = G.C.WHITE, shadow = true } }
                                                                    }
                                                                },
                                                                {
                                                                    n = G.UIT.R,
                                                                    config = { align = "cm", maxw = 1.3 },
                                                                    nodes = {
                                                                        { n = G.UIT.T, config = { text = localize('b_next_round_2'), scale = 0.4, colour = G.C.WHITE, shadow = true } }
                                                                    }
                                                                }
                                                            }
                                                        },
                                                    }
                                                },
                                                {
                                                    n = G.UIT.R,
                                                    config = { align = "cm", minw = 2.8, minh = 1.6, r = 0.15, colour = G.C.GREEN, button = 'reroll_shop', func = 'can_reroll', hover = true, shadow = true },
                                                    nodes = {
                                                        {
                                                            n = G.UIT.R,
                                                            config = { align = "cm", padding = 0.07, focus_args = { button = 'x', orientation = 'cr' }, func = 'set_button_pip' },
                                                            nodes = {
                                                                {
                                                                    n = G.UIT.R,
                                                                    config = { align = "cm", maxw = 1.3 },
                                                                    nodes = {
                                                                        { n = G.UIT.T, config = { text = localize('k_reroll'), scale = 0.4, colour = G.C.WHITE, shadow = true } },
                                                                    }
                                                                },
                                                                {
                                                                    n = G.UIT.R,
                                                                    config = { align = "cm", maxw = 1.3, minw = 1 },
                                                                    nodes = {
                                                                        { n = G.UIT.T, config = { ref_table = G.GAME.current_round, ref_value = 'mstg_brown_deck_rerolls', scale = 0.75, colour = G.C.WHITE, shadow = true } },
                                                                        { n = G.UIT.T, config = { text = localize('mstg_rerolls_left'), scale = 0.7, colour = G.C.WHITE, shadow = true } },
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                },
                                            }
                                        },
                                        {
                                            n = G.UIT.C,
                                            config = { align = "cm", padding = 0.2, r = 0.2, colour = G.C.L_BLACK, emboss = 0.05, minw = 8.2 },
                                            nodes = {
                                                { n = G.UIT.O, config = { object = G.shop_jokers } },
                                            }
                                        },
                                    }
                                },
                                { n = G.UIT.R, config = { align = "cm", minh = 0.2 }, nodes = {} },
                                {
                                    n = G.UIT.R,
                                    config = { align = "cm", padding = 0.1 },
                                    nodes = {
                                        {
                                            n = G.UIT.C,
                                            config = { align = "cm", padding = 0.15, r = 0.2, colour = G.C.L_BLACK, emboss = 0.05 },
                                            nodes = {
                                                {
                                                    n = G.UIT.C,
                                                    config = { align = "cm", padding = 0.2, r = 0.2, colour = G.C.BLACK, maxh = G.shop_vouchers.T.h + 0.4 },
                                                    nodes = {
                                                        { n = G.UIT.T, config = { text = localize { type = 'variable', key = 'ante_x_voucher', vars = { G.GAME.round_resets.ante } }, scale = 0.45, colour = G.C.L_BLACK, vert = true } },
                                                        { n = G.UIT.O, config = { object = G.shop_vouchers } },
                                                    }
                                                },
                                            }
                                        },
                                        {
                                            n = G.UIT.C,
                                            config = { align = "cm", padding = 0.15, r = 0.2, colour = G.C.L_BLACK, emboss = 0.05 },
                                            nodes = {
                                                { n = G.UIT.O, config = { object = G.shop_booster } },
                                            }
                                        },
                                    }
                                }
                            }
                        },

                    }, false)
                }
            }
            return t
        end
'''
match_indent = true
times = 1
