[manifest]
version = "1.0.0"
dump_lua = true
priority = 5

# Introduce a new Base Normal variable
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "normal = 1,"
position = "after"
payload = '''
base_normal = 1,
'''
match_indent = true
times = 1